server:
  port: 8082
#配置数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1111
  application:
    name: service-provider #将来会做为微服务的名称

mybatis:
  #pojo别名扫描包
  type-aliases-package: com.xiokary.server.domain
  #加载mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
